// Generated by CoffeeScript 1.6.3
define(['lib/jquery'], function($) {
  var view;
  view = {
    template: function(city) {
      var i, situation, _i, _len, _ref, _results;
      $('#city-intro').html("<h1>" + city.description + "</h1>");
      _ref = city.situations;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        situation = _ref[i];
        _results.push($('#situations .situation-' + i).html("<h1>" + situation.description + "</h1>"));
      }
      return _results;
    }
  };
  return view;
});
