// Generated by CoffeeScript 1.6.3
define(['lib/jquery'], function($) {
  var view;
  view = {
    template: function(situation) {
      return $('#situation-intro').html("<h1>" + situation.description + "</h1>");
    }
  };
  return view;
});
