// Generated by CoffeeScript 1.6.3
define(['data/source', 'cityView', 'situationView', 'lib/jquery'], function(data, cityView, situationView, $) {
  var currentCityIndex, currentSectionIndex, currentSituationIndex;
  currentSectionIndex = 0;
  currentCityIndex = 0;
  currentSituationIndex = 0;
  this.setCity = function(city) {
    cityView.template(city);
  };
  this.setSituation = function(situation) {
    situationView.template(situation);
  };
  this.onSectionLeave = function(index, direction) {
    if (direction === 'down') {
      currentSectionIndex++;
      switch (index) {
        case 2:
          this.setCity(data[currentCityIndex]);
          break;
        case 4:
          this.setSituation(data[currentCityIndex].situations[currentSituationIndex]);
      }
    }
    if (direction === 'up') {
      currentSectionIndex--;
    }
  };
  this.onSlideLeave = function(anchorLink, index, slideIndex, direction) {
    switch (index) {
      case 2:
        if (direction === "right") {
          currentCityIndex++;
        }
        if (direction === "left") {
          currentCityIndex--;
        }
        currentCityIndex = currentCityIndex % data.length;
        break;
      case 4:
        if (direction === "right") {
          currentSituationIndex++;
        }
        if (direction === "left") {
          currentSituationIndex--;
        }
        currentSituationIndex = currentSituationIndex % data[currentCityIndex].situations.length;
    }
  };
  return this;
});
